#!/usr/bin/env python3
"""Build kg/math.json and viewer/kg-data.js from kg/spine.json + kg/bands/*.json.

The spine is the source of truth for which nodes exist; band files carry the content.
Nodes present in the spine but missing from every band are included as stubs (flagged
"stub": true) so the viewer and tutor can still see them.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main() -> int:
    spine = json.loads((ROOT / "kg" / "spine.json").read_text())
    spine_ids = [n["id"] for n in spine["nodes"]]
    spine_by_id = {n["id"]: n for n in spine["nodes"]}

    detailed = {}
    for band_file in sorted((ROOT / "kg" / "bands").glob("*.json")):
        band = json.loads(band_file.read_text())
        for node in band.get("nodes", []):
            if node["id"] in detailed:
                print(f"WARN: {node['id']} defined in two band files; keeping first", file=sys.stderr)
                continue
            detailed[node["id"]] = node

    nodes = []
    stubs = 0
    for nid in spine_ids:
        if nid in detailed:
            nodes.append(detailed[nid])
        else:
            stub = dict(spine_by_id[nid])
            stub.update({"stub": True, "prerequisites": [], "misconceptions": [], "questions": []})
            nodes.append(stub)
            stubs += 1

    extras = sorted(set(detailed) - set(spine_ids))
    if extras:
        print(f"WARN: band nodes not in spine (ignored): {extras}", file=sys.stderr)

    graph = {
        "version": spine["version"],
        "subject": spine["subject"],
        "strands": spine["strands"],
        "built_from": {"spine": "kg/spine.json", "bands": "kg/bands/*.json"},
        "nodes": nodes,
    }
    out = ROOT / "kg" / "math.json"
    out.write_text(json.dumps(graph, indent=2, ensure_ascii=False) + "\n")

    # Compact payload for the self-contained viewer (no questions - keeps the file small
    # and keeps answer keys out of student-facing pages).
    viewer_nodes = []
    for n in nodes:
        viewer_nodes.append({
            "id": n["id"],
            "title": n["title"],
            "grade": n["grade"],
            "strand": n["strand"],
            "description": n.get("description", ""),
            "prereqs": n.get("prerequisites", []),
            "outcomes": n.get("learning_outcomes", []),
            "difficulty": n.get("difficulty", 0),
            "est_minutes": n.get("est_minutes", 0),
            "stub": n.get("stub", False),
        })
    payload = {"strands": spine["strands"], "nodes": viewer_nodes}
    js = "// Generated by scripts/build_kg.py - do not edit by hand\nwindow.KG_DATA = " \
        + json.dumps(payload, ensure_ascii=False) + ";\n"
    (ROOT / "viewer" / "kg-data.js").write_text(js)

    print(f"Built kg/math.json: {len(nodes)} nodes ({stubs} stubs), "
          f"{sum(len(n.get('questions', [])) for n in nodes)} questions, "
          f"{sum(len(n.get('misconceptions', [])) for n in nodes)} misconceptions")
    print("Built viewer/kg-data.js")
    return 0


if __name__ == "__main__":
    sys.exit(main())
