#!/usr/bin/env python3
"""Export a student's mastery overlay for the viewer: viewer/student-data.js.

Usage: python3 scripts/export_student_overlay.py S001

Status per node:
  mastered    - score >= 0.8 with conceptual_ok
  in-progress - some evidence but below mastery
  frontier    - no evidence yet, but ALL prerequisites mastered (ready to learn now)
  locked      - some prerequisite not yet mastered
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 1
    sid = sys.argv[1]
    profile_file = ROOT / "students" / sid / "profile.json"
    if not profile_file.exists():
        print(f"no profile at {profile_file}")
        return 1
    profile = json.loads(profile_file.read_text())
    graph = json.loads((ROOT / "kg" / "math.json").read_text())

    mastery = profile.get("mastery", {})

    def mastered(nid: str) -> bool:
        m = mastery.get(nid)
        return bool(m and m.get("score", 0) >= 0.8 and m.get("conceptual_ok", False))

    def pid(p):
        return p if isinstance(p, str) else p["id"]

    def hard_prereqs(n):
        # bare-string edges are hard by definition; typed soft edges recommend, not gate
        return [pid(p) for p in n.get("prerequisites", [])
                if isinstance(p, str) or p.get("strength", "hard") == "hard"]

    status = {}
    for n in graph["nodes"]:
        nid = n["id"]
        hard = hard_prereqs(n)
        if mastered(nid):
            status[nid] = "mastered"
        elif nid in mastery:
            status[nid] = "in-progress"
        elif all(mastered(p) for p in hard):
            status[nid] = "frontier"
        else:
            status[nid] = "locked"

    payload = {
        "student": sid,
        "grade": profile.get("grade"),
        "status": status,
        "scores": {k: round(v.get("score", 0), 2) for k, v in mastery.items()},
    }
    js = "// Generated by scripts/export_student_overlay.py - do not edit by hand\n" \
         "window.STUDENT_DATA = " + json.dumps(payload, ensure_ascii=False) + ";\n"
    (ROOT / "viewer" / "student-data.js").write_text(js)
    counts = {}
    for s in status.values():
        counts[s] = counts.get(s, 0) + 1
    print(f"Wrote viewer/student-data.js for {sid}: {counts}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
